# Site wide configuration

title: theowinter.ch
description: A computer science student from Switzerland who's passionate about programming and photography.
logo: site-logo.png # 120x120 px default image used for Twitter summary card
teaser: default_article_thumbnail.gif # 400x250 px default teaser image used in image archive grid
locale: en
url: https://theowinter.ch

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge

# Site owner
owner:
  name: Theo Winter
  email: theo@w1nter.com
  googleplus: +TheoWinterCH
  github: aerobless
  twitter: TheodorWinter
  google:
    ad-client:
    ad-slot:
  bio: A computer science student from Switzerland who's passionate about programming and photography.
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: theowinterch

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

# Analytics and webmaster tools stuff goes here
google_analytics: UA-38005810-1
google_verify: -Nqci8py-NO2xtbUsuUEMgo1cMYeX8mDOYjgBzPXP_0
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 0B0B2020A81729A7AF0981C047A8984C

#ExifTag
#https://github.com/benib/jekyll-exiftag
exiftag:
 sources:
   - images/photography

#MiniMagick
#https://github.com/zroger/jekyll-minimagick
mini_magick:
    photography:
        source: images/photography
        destination: images/photography/thumbnails
        resize: "1280x720"
    headers:
        source: images/headers
        destination: images/headers/thumbnails
        resize: "594x250"
        crop: "400x250+-0.5+-0.5"

#TODO:
# .htaccess --> error404
# timezone
# google+ & github social prüfen
# sitemap
