markdown: redcarpet
pygments: true

title_tag_text: theowinter.ch
h1_tag_text: theowinter.ch

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]

#Upload with glynn
ftp_host: 'ftp.theowinter.ch'
ftp_dir: '/'
ftp_passive: false
ftp_username: 'glynn@theowinter.ch' 